"""LightGBM learning-to-rank model (train offline, load at runtime for Vercel)."""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np

from recommender.features import FEATURE_NAMES

logger = logging.getLogger(__name__)

try:
    import lightgbm as lgb
except Exception as exc:  # ImportError, OSError on some serverless runtimes
    lgb = None  # type: ignore[assignment]
    logger.warning("LightGBM unavailable (%s); using hybrid fallback.", exc)

MODEL_DIR = Path(__file__).parent / "models"
DEFAULT_MODEL_PATH = MODEL_DIR / "lgb_ranker.txt"


def _load_model_string() -> str | None:
    if DEFAULT_MODEL_PATH.is_file():
        return DEFAULT_MODEL_PATH.read_text(encoding="utf-8")
    try:
        from recommender.model_bundle import MODEL_STR  # auto-generated

        return MODEL_STR
    except ImportError:
        return None


def train_ranker(
    X: np.ndarray,
    y: np.ndarray,
    group: list[int],
    model_path: Path = DEFAULT_MODEL_PATH,
) -> object:
    """Train LambdaRank model and persist to disk (+ embedded bundle for Vercel)."""
    if lgb is None:
        raise RuntimeError("LightGBM is not installed")

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    train_set = lgb.Dataset(X, label=y, group=group, feature_name=FEATURE_NAMES)
    params = {
        "objective": "lambdarank",
        "metric": "ndcg",
        "ndcg_at": [5],
        "learning_rate": 0.05,
        "num_leaves": 15,
        "min_data_in_leaf": 5,
        "verbose": -1,
        "seed": 42,
    }
    booster = lgb.train(params, train_set, num_boost_round=80)
    model_text = booster.model_to_string()
    model_path.write_text(model_text, encoding="utf-8")

    bundle_path = Path(__file__).parent / "model_bundle.py"
    bundle_path.write_text(
        '"""Auto-generated by scripts/train_ranker.py — do not edit."""\n\n'
        f"MODEL_STR = {model_text!r}\n",
        encoding="utf-8",
    )
    return booster


def load_ranker(model_path: Path = DEFAULT_MODEL_PATH):
    if lgb is None:
        return None
    try:
        model_str = _load_model_string()
        if not model_str:
            return None
        return lgb.Booster(model_str=model_str)
    except Exception as exc:
        logger.warning("Failed to load LightGBM ranker (%s); using hybrid fallback.", exc)
        return None


class LightGBMRanker:
    def __init__(self, model_path: Path = DEFAULT_MODEL_PATH):
        self.model_path = model_path
        self.model = load_ranker(model_path)
        self._load_error: str | None = None
        if lgb is None:
            self._load_error = "lightgbm_not_available"
        elif self.model is None:
            self._load_error = "model_not_loaded"

    @property
    def is_loaded(self) -> bool:
        return self.model is not None

    def predict_scores(self, X: np.ndarray) -> np.ndarray:
        if self.model is None:
            raise RuntimeError("LightGBM ranker model is not loaded")
        return self.model.predict(X)
